### ISSUE TITLE
PSFree 

### ISSUE THREAD

**Issue by KarimosDz** [GamerHack/GamerHack.github.io#5]
Is this a page that supports PSFree?
https://gamerhack.github.io/900goldhen/index.html

**Comment by GamerHack** [comment]
The only host with support for psfree is 9.00v4

**Comment by KarimosDz** [comment]
> The only host with support for psfree is 9.00v4

you can add psfree like this page
https://gamerhack.github.io/900goldhen/index.html
Auto Loading GoldHEN Only
